Repository pax-app/Wiki, pull requests merged in 2019-08, with the labels that each got.

#29 Resolve issue #2
  _sidebar.md
  assets/Artumentacaov1.png
  assets/Artumentacaov2.png
  assets/rp_geral_v1.png
  assets/rp_geral_v2.png
  docs/DS/dinamica-e-seminario-1/5W2H.md
  docs/DS/dinamica-e-seminario-1/Argumentacao.md
  docs/DS/dinamica-e-seminario-1/Benchmarking.md
  docs/DS/dinamica-e-seminario-1/Briefing.md
  docs/DS/dinamica-e-seminario-1/CurvadeValor.md
  docs/DS/dinamica-e-seminario-1/Entrevista.md
  docs/DS/dinamica-e-seminario-1/MapaMental.md
  docs/DS/dinamica-e-seminario-1/README.md
  docs/DS/dinamica-e-seminario-1/RichPicture.md
  index.html
Labels: Definição de projeto, Documentação

#35 Resolve Issue #18
  _sidebar.md
  docs/DS/dinamica-e-seminario-1/Brainstorm.md
Labels: Definição de projeto, Documentação, Sprint 01

#33 Resolve issue #17
  assets/rich-pictures/rp_usuario_v1.jpg
  assets/rich-pictures/rp_usuario_v2.png
  assets/rp_usuario_v2.jpg
  docs/DS/dinamica-e-seminario-1/RichPicture.md
Labels: Definição de projeto, Documentação, Sprint 01

#36 Add Sentiment vs. Productivity Analysis
  docs/DS/dinamica-e-seminario-1/SentimentosProdutividade.md
Labels: Definição de projeto, Documentação, Scrum Master, Sprint 01

#37 Add Quiz Analysis
  _sidebar.md
  docs/DS/dinamica-e-seminario-1/AnaliseQuestionario.md
  docs/DS/dinamica-e-seminario-1/README.md
  docs/iniciativas-extras/SentimentosProdutividade.md
Labels: Definição de projeto, Documentação, Scrum Master, Sprint 01

#38 Resolve issue #16
  assets/rich-pictures/rp_prestador_servico.png
  docs/DS/dinamica-e-seminario-1/RichPicture.md
Labels: Definição de projeto, Documentação, Sprint 01

#39 Gerencia
  _sidebar.md
  assets/css/typography.css
  assets/icons/comunication/drive.png
  assets/icons/comunication/github.png
  assets/icons/comunication/hangouts.jpeg
  assets/icons/comunication/hangouts.png
  assets/icons/comunication/telegram.png
  assets/icons/comunication/zenhub.png
  assets/infographic.png
  docs/DS/dinamica-e-seminario-1/AnaliseQuestionario.md
  docs/DS/dinamica-e-seminario-1/DefinicoesDeProjeto.md
  docs/DS/dinamica-e-seminario-1/README.md
  docs/iniciativas-extras/CODE_OF_CONDUCT.md
  docs/iniciativas-extras/CONTRIBUTING.md
  docs/iniciativas-extras/ISSUE_TEMPLATE.md
  docs/iniciativas-extras/Organizacao.md
  docs/iniciativas-extras/PULL_REQUEST_TEMPLATE.md
  docs/iniciativas-extras/README.md
  docs/iniciativas-extras/sprint_plaining_model.md
  docs/iniciativas-extras/sprint_review_model.md
  index.html
Labels: Definição de projeto, Documentação, Scrum Master, Sprint 01
