Repository pax-app/Wiki, pull requests merged in 2019-09, with the labels that each got.

#57 added styleguide
  _sidebar.md
  assets/styleguide.png
  docs/iniciativas-extras/style_guide.md
Labels: Definição de projeto, Documentação, Sprint 02

#58 NFR
  _sidebar.md
  docs/DS/dinamica-e-seminario-2/README.md
  docs/DS/dinamica-e-seminario-2/nfr.md
Labels: Documentação, Sprint 02

#60 Glossário da aplicação
  docs/DS/dinamica-e-seminario-1/glossario.md
Labels: Definição de projeto, Sprint 02

#63 resolve issue #45
  _sidebar.md
  docs/DS/dinamica-e-seminario-2/metodologia.md
Labels: Documentação, Sprint 02

#77 [#41] Added missing wireframes
  assets/wireframes/FormularioPrestador.png
  assets/wireframes/MenuDoUsuario.png
  assets/wireframes/MenuPrestador.png
  assets/wireframes/MenuPrestadorAberto.png
  assets/wireframes/TelaCadastroSucessoPrestador.png
  assets/wireframes/TelaInformacoesPrestador.png
  assets/wireframes/TelaInstrucoesCadastroPrestador.png
  docs/DS/dinamica-e-seminario-2/wireframes.md
Labels: Definição de projeto, Documentação, Sprint 02

#82 Adding diagrams to the wiki.
  _sidebar.md
  docs/DS/dinamica-e-seminario-2/Diagramas.md
Labels: Documentação, Sprint 03

#83 Documentação Sprint 02
  .gitignore
  _sidebar.md
  docs/iniciativas-extras/documentacao_sprints/README.md
  docs/iniciativas-extras/documentacao_sprints/plaining_02.md
  docs/iniciativas-extras/documentacao_sprints/review_01.md
  docs/iniciativas-extras/documentacao_sprints/review_02.md
Labels: Documentação, Scrum Master, Sprint 03

#79 Evolução do glossário para Léxico
  _sidebar.md
  docs/DS/dinamica-e-seminario-2/README.md
  docs/DS/dinamica-e-seminario-2/glossario.md
  docs/DS/dinamica-e-seminario-2/lexico.md
Labels: Definição de projeto, Documentação, Sprint 03

#78 75 priorizacao
  _sidebar.md
  assets/wireframes/esio1.jpg
  assets/wireframes/esio2.jpg
  assets/wireframes/esio3.jpg
  docs/DS/dinamica-e-seminario-2/Backlog.md
  docs/DS/dinamica-e-seminario-2/priorizacao.md
  docs/DS/dinamica-e-seminario-2/wireframes.md
Labels: Documentação, Product Owner, Sprint 03

#85 Adding diagrams to principal menu.
  docs/DS/dinamica-e-seminario-2/Diagramas.md
  docs/DS/dinamica-e-seminario-2/README.md
Labels: Documentação, Sprint 03

#96 Documentação Sprint 03
  _sidebar.md
  docs/iniciativas-extras/documentacao_sprints/README.md
  docs/iniciativas-extras/documentacao_sprints/plaining_03.md
  docs/iniciativas-extras/documentacao_sprints/review_03.md
Labels: Documentação, Scrum Master, Sprint 03

#97 93 digrama pacotes
  _sidebar.md
  assets/pacotesBackFlask.png
  assets/pacotesBackNode.png
  assets/pacotesFront.png
  assets/wireframes/a.jpg
  assets/wireframes/kisspng-bicycle-tires-cheng-shin-rubber-electric-bicycle-re-volt-maxxis-international-5b652378f14292.0319083515333548729882.jpg
  assets/wireframes/kisspng-tread-bicycle-tires-car-tyre-5afe2d9fb909d5.4331297415266072637579.jpg
  docs/DS/dinamica-e-seminario-3/DiagramaPacotes.md
Labels: Sprint 04

#98 Diagramas de Banco de Dados
  _sidebar.md
  assets/database/Conceitual_Pax_v1.brM3
  assets/database/Conceitual_Pax_v1.png
  assets/database/Logico_Pax_v1.brM3
  assets/database/Logico_Pax_v1.png
  docs/DS/dinamica-e-seminario-3/DiagramasBancoDeDados.md
  docs/DS/dinamica-e-seminario-3/README.md
Labels: Documentação, Sprint 04

#99 Documento de Arquitetura v0.0
  .gitignore
  _sidebar.md
  assets/arquitetura/representacao_v1.png
  docs/.nojekyll
  docs/DS/dinamica-e-seminario-1/Benchmarking.md
  docs/DS/dinamica-e-seminario-3/DocumentoDeArquitetura.md
  docs/DS/dinamica-e-seminario-3/README.md
  docs/README.md
  docs/index.html
Labels: Documentação, Sprint 04

#100 Diagrama de casos de uso
  assets/arquitetura/PAXCasosDeUsoV2.png
  docs/DS/dinamica-e-seminario-3/DocumentoDeArquitetura.md
Labels: Documentação, Sprint 04

#113 95 backend state diagram
  _sidebar.md
  assets/diagrama_estados_chat.png
  assets/diagrama_estados_payment.png
  docs/DS/dinamica-e-seminario-3/DiagramaEstados.md
  docs/DS/dinamica-e-seminario-3/README.md
Labels: Definição de projeto, DevOps, Documentação, Sprint 04

#117 68 usability test wireframe
  _sidebar.md
  assets/pacotesBackFlask2.png
  assets/teste-usabilidade/genero.png
  assets/teste-usabilidade/graf1.png
  assets/teste-usabilidade/users.png
  docs/DS/dinamica-e-seminario-3/DiagramaPacotes.md
  docs/DS/dinamica-e-seminario-3/DiagramasBancoDeDados.md
  docs/DS/dinamica-e-seminario-3/README.md
  docs/DS/dinamica-e-seminario-3/TesteDeUsabilidadeWireframe.md
Labels: Sprint 04, Sprint 05

#115 Creating Sequence Diagram document and adding Login diagram.
  _sidebar.md
  assets/diagramas_sequencia/Login.png
  docs/DS/dinamica-e-seminario-3/DiagramaSequencia.md
  docs/DS/dinamica-e-seminario-3/README.md
Labels: Documentação, Sprint 04

#118 Documentação Sprint 04
  _sidebar.md
  docs/iniciativas-extras/documentacao_sprints/README.md
  docs/iniciativas-extras/documentacao_sprints/plaining_04.md
  docs/iniciativas-extras/documentacao_sprints/review_04.md
Labels: Documentação, Scrum Master, Sprint 04

#120 119 pontuacao backlog
  _sidebar.md
  docs/DS/dinamica-e-seminario-2/Backlog.md
  docs/DS/dinamica-e-seminario-2/priorizacao.md
  docs/DS/dinamica-e-seminario-3/DocumentoDeArquitetura.md
  docs/DS/dinamica-e-seminario-3/PontuacaoBacklog.md
  docs/DS/dinamica-e-seminario-3/README.md
Labels: Sprint 05

#123 Passagem dos casos de uso para um documento próprio
  _sidebar.md
  assets/arquitetura/PAXCasosDeUsoV0.png
  assets/arquitetura/PAXCasosDeUsoV1.png
  docs/DS/dinamica-e-seminario-3/DiagramaCasosDeUso.md
Labels: Documentação

#124 Improve PR template
  .github/pull_request_template.md
Labels: Sprint 05

#125 Diagrama de Bancos V2
  assets/database/Conceitual_Pax_v2.brM3
  assets/database/Conceitual_Pax_v2.png
  assets/database/Logico_Pax_v2.brM3
  assets/database/Logico_Pax_v2.png
  docs/DS/dinamica-e-seminario-3/DiagramasBancoDeDados.md
Labels: Documentação, Sprint 05

#126 121 state diagram
  assets/Diagrama_de_estados_chat_v2.png
  assets/Diagrama_de_estados_payment_v2.png
  docs/DS/dinamica-e-seminario-3/DiagramaEstados.md
Labels: Documentação, Sprint 05

#127 112 process diagram update(BPMN)
  docs/DS/dinamica-e-seminario-2/Diagramas.md
Labels: Documentação, Sprint 05

#128 107 diagram sequence v2
  docs/DS/dinamica-e-seminario-3/DiagramaSequencia.md
Labels: Documentação, Sprint 05

#133 106 roadmap
  _sidebar.md
  assets/DiagramaContextoV1.png
  assets/DiagramaContextoV2.png
  assets/Rectangle.png
  assets/roadmap.png
  docs/DS/dinamica-e-seminario-3/DiagramaContexto.md
  docs/DS/dinamica-e-seminario-3/DocumentoDeArquitetura.md
  docs/DS/dinamica-e-seminario-3/README.md
  docs/DS/dinamica-e-seminario-3/Roadmap.md
Labels: Sprint 05

#134 Referências da Wiki Formato ABNT
  docs/DS/dinamica-e-seminario-1/5W2H.md
  docs/DS/dinamica-e-seminario-1/AnaliseQuestionario.md
  docs/DS/dinamica-e-seminario-1/Argumentacao.md
  docs/DS/dinamica-e-seminario-1/Benchmarking.md
  docs/DS/dinamica-e-seminario-1/Brainstorming.md
  docs/DS/dinamica-e-seminario-1/Briefing.md
  docs/DS/dinamica-e-seminario-1/CurvadeValor.md
  docs/DS/dinamica-e-seminario-1/Entrevista.md
  docs/DS/dinamica-e-seminario-1/RichPicture.md
  docs/DS/dinamica-e-seminario-2/Backlog.md
  docs/DS/dinamica-e-seminario-2/Diagramas.md
  docs/DS/dinamica-e-seminario-2/DocDeVisao.md
  docs/DS/dinamica-e-seminario-2/PrototipoBaixaFidelidade.md
  docs/DS/dinamica-e-seminario-2/Tecnologias.md
  docs/DS/dinamica-e-seminario-2/lexico.md
  docs/DS/dinamica-e-seminario-2/nfr.md
  docs/DS/dinamica-e-seminario-2/priorizacao.md
  docs/DS/dinamica-e-seminario-2/style_guide.md
  docs/DS/dinamica-e-seminario-3/DiagramaCasosDeUso.md
  docs/DS/dinamica-e-seminario-3/DiagramaClasses.md
  docs/DS/dinamica-e-seminario-3/DiagramaContexto.md
  docs/DS/dinamica-e-seminario-3/DiagramaEstados.md
  docs/DS/dinamica-e-seminario-3/DiagramaImplantacao.md
  docs/DS/dinamica-e-seminario-3/DiagramaPacotes.md
  docs/DS/dinamica-e-seminario-3/DiagramaSequencia.md
  docs/DS/dinamica-e-seminario-3/DiagramasBancoDeDados.md
  docs/DS/dinamica-e-seminario-3/DocumentoDeArquitetura.md
  docs/DS/dinamica-e-seminario-3/ManualIdentidadeVisual.md
  docs/DS/dinamica-e-seminario-3/PontuacaoBacklog.md
  docs/DS/dinamica-e-seminario-3/PrototipoMediaFidelidade.md
  docs/DS/dinamica-e-seminario-3/Roadmap.md
  docs/DS/dinamica-e-seminario-3/TesteDeUsabilidadeWireframe.md
  docs/iniciativas-extras/SentimentosProdutividade.md
  modelo.md
Labels: Documentação, Sprint 05

#155 Diagrama de Banco de Dados V3
  assets/database/Conceitual_Pax_v3.brM3
  assets/database/Conceitual_Pax_v3.png
  assets/database/Logico_Pax_v3.brM3
  assets/database/Logico_Pax_v3.png
  docs/DS/dinamica-e-seminario-3/DiagramasBancoDeDados.md
Labels: Documentação, Sprint 06, improvement

#156 #151 Add backlog poits v2
  docs/DS/dinamica-e-seminario-3/PontuacaoBacklog.md
Labels: Sprint 06
